import type { EntertainmentContent, Genre } from './types';

export const genres: Genre[] = [
  "action", "adventure", "biopic", "comedy", "crime", 
  "documentary", "drama", "fantasy", "heartbreak", "horror", 
  "mystery", "romcom", "scifi", "thriller"
];

export const mockContent: EntertainmentContent[] = [
  {
    id: '1',
    title: 'Stranger Things',
    description: 'When a young boy vanishes, a small town uncovers a mystery involving secret experiments, terrifying supernatural forces, and one strange little girl.',
    category: 'webseries',
    genres: ['scifi', 'horror', 'thriller', 'mystery'],
    imdbRating: 8.7,
    rottenTomatoesRating: 92,
    imageUrl: 'https://picsum.photos/400/600',
    imageHint: 'mystery forest',
  },
  {
    id: '2',
    title: 'Inception',
    description: 'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.',
    category: 'movie',
    genres: ['action', 'adventure', 'scifi', 'thriller'],
    imdbRating: 8.8,
    rottenTomatoesRating: 87,
    imageUrl: 'https://picsum.photos/400/601',
    imageHint: 'city architecture',
  },
  {
    id: '3',
    title: 'The Office',
    description: 'A mockumentary on a group of typical office workers, where the workday consists of ego clashes, inappropriate behavior, and tedium.',
    category: 'tv show',
    genres: ['comedy', 'romcom'],
    imdbRating: 9.0,
    rottenTomatoesRating: 81,
    imageUrl: 'https://picsum.photos/400/602',
    imageHint: 'office supplies',
  },
  {
    id: '4',
    title: 'Blade Runner 2049',
    description: 'Young Blade Runner K\'s discovery of a long-buried secret leads him to track down former Blade Runner Rick Deckard, who\'s been missing for thirty years.',
    category: 'movie',
    genres: ['scifi', 'action', 'mystery', 'thriller'],
    imdbRating: 8.0,
    rottenTomatoesRating: 88,
    imageUrl: 'https://picsum.photos/400/603',
    imageHint: 'futuristic city',
  },
  {
    id: '5',
    title: 'Fleabag',
    description: 'A dry-witted woman, known only as Fleabag, has no filter as she navigates life and love in London while trying to cope with tragedy.',
    category: 'webseries',
    genres: ['comedy', 'drama', 'heartbreak'],
    imdbRating: 8.7,
    rottenTomatoesRating: 100,
    imageUrl: 'https://picsum.photos/400/604',
    imageHint: 'woman portrait',
  },
  {
    id: '6',
    title: 'Parasite',
    description: 'Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.',
    category: 'movie',
    genres: ['thriller', 'drama', 'comedy', 'crime'],
    imdbRating: 8.5,
    rottenTomatoesRating: 99,
    imageUrl: 'https://picsum.photos/400/605',
    imageHint: 'modern house',
  },
  {
    id: '7',
    title: 'Breaking Bad',
    description: 'A high school chemistry teacher diagnosed with inoperable lung cancer turns to manufacturing and selling methamphetamine in order to secure his family\'s future.',
    category: 'tv show',
    genres: ['drama', 'thriller', 'crime'],
    imdbRating: 9.5,
    rottenTomatoesRating: 96,
    imageUrl: 'https://picsum.photos/400/606',
    imageHint: 'desert landscape',
  },
  {
    id: '8',
    title: 'The Lord of the Rings',
    description: 'A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle-earth from the Dark Lord Sauron.',
    category: 'movie',
    genres: ['fantasy', 'adventure', 'action'],
    imdbRating: 8.8,
    rottenTomatoesRating: 91,
    imageUrl: 'https://picsum.photos/400/607',
    imageHint: 'fantasy landscape',
  },
  {
    id: '9',
    title: 'Chernobyl',
    description: 'In April 1986, an explosion at the Chernobyl nuclear power plant in the Union of Soviet Socialist Republics becomes one of the world\'s worst man-made catastrophes.',
    category: 'webseries',
    genres: ['drama', 'thriller', 'biopic'],
    imdbRating: 9.4,
    rottenTomatoesRating: 95,
    imageUrl: 'https://picsum.photos/400/608',
    imageHint: 'industrial building',
  },
  {
    id: '10',
    title: 'Planet Earth II',
    description: 'David Attenborough returns in a new wildlife documentary that shows life in a variety of habitats.',
    category: 'tv show',
    genres: ['documentary'],
    imdbRating: 9.5,
    rottenTomatoesRating: 98,
    imageUrl: 'https://picsum.photos/400/609',
    imageHint: 'nature animals',
  },
  {
    id: '11',
    title: 'Spirited Away',
    description: 'During her family\'s move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods, witches, and spirits, and where humans are changed into beasts.',
    category: 'movie',
    genres: ['fantasy', 'adventure', 'mystery'],
    imdbRating: 8.6,
    rottenTomatoesRating: 97,
    imageUrl: 'https://picsum.photos/400/610',
    imageHint: 'anime temple',
  },
  {
    id: '12',
    title: 'Black Mirror',
    description: 'An anthology series exploring a twisted, high-tech multiverse where humanity\'s greatest innovations and darkest instincts collide.',
    category: 'webseries',
    genres: ['scifi', 'thriller', 'drama'],
    imdbRating: 8.7,
    rottenTomatoesRating: 84,
    imageUrl: 'https://picsum.photos/400/611',
    imageHint: 'abstract technology',
  },
   {
    id: '13',
    title: 'The Mandalorian',
    description: 'The travels of a lone bounty hunter in the outer reaches of the galaxy, far from the authority of the New Republic.',
    category: 'webseries',
    genres: ['action', 'adventure', 'scifi', 'fantasy'],
    imdbRating: 8.7,
    rottenTomatoesRating: 93,
    imageUrl: 'https://picsum.photos/400/612',
    imageHint: 'space bounty-hunter',
  },
  {
    id: '14',
    title: 'When Harry Met Sally...',
    description: 'Harry and Sally have known each other for years, and are very good friends, but they fear sex would ruin the friendship.',
    category: 'movie',
    genres: ['romcom', 'comedy', 'drama'],
    imdbRating: 7.7,
    rottenTomatoesRating: 91,
    imageUrl: 'https://picsum.photos/400/613',
    imageHint: 'autumn park',
  },
  {
    id: '15',
    title: 'Mindhunter',
    description: 'In the late 1970s, two FBI agents expand criminal science by delving into the psychology of murder and getting uneasily close to all-too-real monsters.',
    category: 'tv show',
    genres: ['crime', 'thriller', 'drama', 'mystery'],
    imdbRating: 8.6,
    rottenTomatoesRating: 97,
    imageUrl: 'https://picsum.photos/400/614',
    imageHint: 'dark interrogation',
  }
];
